function dataOne(data1) {
    var s1 = data1.replace(/args#/g, "arguments")
    s1 = s1.replace(/aw#/g, "await")
    s1 = s1.replace(/br#/g, "break")
    s1 = s1.replace(/cs#/g, "case")
    s1 = s1.replace(/ch#/g, "catch")
    s1 = s1.replace(/cl#/g, "class")
    s1 = s1.replace(/con#/g, "const")
    s1 = s1.replace(/cont#/g, "continue")
    s1 = s1.replace(/dbg#/g, "debugger")
    s1 = s1.replace(/def#/g, "default")
    s1 = s1.replace(/del#/g, "delete")
    s1 = s1.replace(/el#/g, "else")
    s1 = s1.replace(/en#/g, "enum")
    s1 = s1.replace(/ev#/g, "eval")
    s1 = s1.replace(/exp#/g, "export")
    s1 = s1.replace(/ext#/g, "extends")
    s1 = s1.replace(/fal#/g, "false")
    s1 = s1.replace(/fin#/g, "finally")
    s1 = s1.replace(/func#/g, "function")
    s1 = s1.replace(/impl#/g, "implements")
    s1 = s1.replace(/impt#/g, "import")
    s1 = s1.replace(/instof#/g, "instanceof")
    s1 = s1.replace(/intf#/g, "interface")
    s1 = s1.replace(/l#/g, "let")
    s1 = s1.replace(/nw#/g, "new")
    s1 = s1.replace(/pkg#/g, "package")
    s1 = s1.replace(/pri#/g, "private")
    s1 = s1.replace(/pro#/g, "protected")
    s1 = s1.replace(/pub#/g, "public")
    s1 = s1.replace(/rt#/g, "return")
    s1 = s1.replace(/stc#/g, "static")
    s1 = s1.replace(/sp#/g, "super")
    s1 = s1.replace(/sw#/g, "switch")
    s1 = s1.replace(/th#/g, "throw")
    s1 = s1.replace(/tr#/g, "true")
    s1 = s1.replace(/tpof#/g, "typeof")
    s1 = s1.replace(/v#/g, "var")
    s1 = s1.replace(/vo#/g, "void")
    s1 = s1.replace(/wh#/g, "while")
    s1 = s1.replace(/wi#/g, "with")
    s1 = s1.replace(/yld#/g, "yield")

    return s1
}

module.exports = dataOne